# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-05 03:21
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0, "ratings shouldn't be negative"), django.core.validators.MaxValueValidator(10, 'the maximum rating is 10')]),
        ),
    ]
